version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: cheese
      POSTGRES_PASSWORD: balls
      POSTGRES_DB: db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080