version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - './mongodb:/data/db:cached'
  roboto:
    build: .
    environment:
      PREFIX: '!'
      TOKEN: ''
      MONGO_URL: 'mongodb://mongodb:27017/roboto'
      LOG_LEVEL: 'debug'
      CHANNEL_FILTER: 'blacklist'
      WHITELIST_CHANNELS: ''
      BLACKLIST_CHANNELS: ''
    command: npm run start
