version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
  postgres:
    image: postgres:latest
    ports:
        - 5432:5432

  web:
    build: ./web
    image: roboto-web

  roboto-text:
    build: ./bot
    image: roboto-text
    environment:
      - COMMANDLIST=text
    env_file:
      - .env

  roboto-voice:
    build: ./bot
    image: roboto-voice
    environment:
      - COMMANDLIST=voice
    env_file:
      - .env

  server:
    build: ./server
    image: roboto-server
    ports:
      - 8080:3000