version: '3.7'
services:
  mongodb:
    volumes:
      - './mongodb:/data/db:cached'
      
  postgres:
    environment:
      POSTGRES_USER: cheese             # The initial database username
      POSTGRES_PASSWORD: balls          # The initial database password
      POSTGRES_DB: db                   # The initial database name
      PGDATA: /mnt/data                 # Specifies the directory to mount the database
    volumes:
      - './postgres:/mnt/data:cached'
  
  web:
    command: npm run start
    volumes:
      - './web:/opt/roboto:cached'
  roboto-text:
    command: npm run start:dev
    volumes:
      - './bot:/opt/roboto:cached'
  roboto-voice:
    command: npm run start:dev
    volumes:
      - './bot:/opt/roboto:cached'
  server:
    command: npm run start:dev