version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
  web:
    build: ./web
  roboto-text:
    build: ./bot
    environment:
      - COMMANDLIST=text
  roboto-voice:
    build: ./bot
    environment:
      - COMMANDLIST=voice