version: '3.7'
services:
  mongodb:
    volumes:
      - 'dbdata:/data/db:cached'
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  postgres:
    volumes:
      - 'postgres:/mnt/data:cached'
    secrets:
      - pgEnv
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        
  web:
    command: serve -s build -l 80
    restart: always
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  roboto-text:
    command: npm run start
    restart: always
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  roboto-voice:
    command: npm run start
    restart: always
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  server:
    command: npm run start
    restart: always
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

secrets:
  pgEnv:
    external: true
    name: roboto_PostgresConfig

volumes:
  dbdata:
    external: true              # Defines volume to be specified on the swarm. Needed for relocatable persistent storage.
  pgdata:
    external: true