version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
  web:
    build: ./web
  roboto-text:
    build: ./bot
    environment:
      - COMMANDLIST=text
    env_file:
      - .env
  roboto-voice:
    build: ./bot
    environment:
      - COMMANDLIST=voice
    env_file:
      - .env
  server:
    build: ./server