version: '3.7'
services:
  mongodb:
    volumes:
      - './mongodb:/data/db:cached'
  web:
    command: npm run start
    volumes:
      - './web:/opt/roboto:cached'
  roboto-text:
    command: npm run start:dev
    volumes:
      - './bot:/opt/roboto:cached'
  roboto-voice:
    command: npm run start:dev
    volumes:
      - './bot:/opt/roboto:cached'