version: '3.7'
services:
  mongodb:
    volumes:
      - 'dbdata:/data/db:cached'
  web:
    command: serve -s build -l 80
    restart: always
  roboto-text:
    command: npm run start
    restart: always
  roboto-voice:
    command: npm run start
    restart: always
volumes:
  dbdata: